In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

import statsmodels.api as sm

%matplotlib inline

In [29]:
data_diani = pd.read_csv('Diani_sediment_data.csv')
data_diani

,Habitat,Site name,Average of AGB (g/m2),AGB (g DW m-2),AGCorg (Mg C ha-1),AGCorg (Mg C ha-1).1,Average of BGB (g/m2),BGB (g DW m-2),BGCorg (Mg C ha-1),BGCorg (Mg C ha-1).1
0,Mangrove fringed shoreline,Chale,0.143,50.601557,17.204529,0.172045,1.421,502.830856,170.962491,1.709625
1,Mangrove fringed shoreline,Chale,0.967,342.179759,116.341118,1.163411,0.300,106.157112,36.093418,0.360934
2,Mangrove fringed shoreline,Chale,1.050,371.549894,126.326964,1.263270,5.827,2061.924982,701.054494,7.010545
3,Mangrove fringed shoreline,Chale,0.504,178.343949,60.636943,0.606369,3.676,1300.778485,442.264685,4.422647
4,Mangrove fringed shoreline,Chale,0.546,193.205945,65.690021,0.656900,0.216,76.433121,25.987261,0.259873
...,...,...,...,...,...,...,...,...,...,...
78,Tourist hotels,Neptune,2.576,911.535740,309.922151,3.099222,14.603,5167.374381,1756.907289,17.569073
79,Tourist hotels,Neptune,16.912,5984.430290,2034.706299,20.347063,2.047,724.345364,246.277424,2.462774
80,Tourist hotels,Neptune,0.998,353.149328,120.070771,1.200708,8.171,2891.365888,983.064402,9.830644
81,Tourist hotels,Neptune,1.079,381.811748,129.815994,1.298160,6.114,2163.481953,735.583864,7.355839
82,Tourist hotels,Neptune,3.829,1354.918613,460.672328,4.606723,1.031,364.826610,124.041047,1.240410

In [39]:

data_diani.columns[2]


x = list(data_diani.columns)



x[2] = 'Average_AGB'
x[6] = 'Average_BGB'

data_diani.columns= x
x

['Habitat',
 'Site name',
 'Average_AGB',
 'AGB (g DW m-2)',
 'AGCorg (Mg C ha-1)',
 'AGCorg (Mg C ha-1).1',
 'Average_BGB',
 'BGB (g DW m-2)',
 'BGCorg (Mg C ha-1)',
 'BGCorg (Mg C ha-1).1']

In [31]:
data_diani

,Habitat,Site name,Average_AGB,AGB (g DW m-2),AGCorg (Mg C ha-1),AGCorg (Mg C ha-1).1,Average of BGB (g/m2),BGB (g DW m-2),BGCorg (Mg C ha-1),BGCorg (Mg C ha-1).1
0,Mangrove fringed shoreline,Chale,0.143,50.601557,17.204529,0.172045,1.421,502.830856,170.962491,1.709625
1,Mangrove fringed shoreline,Chale,0.967,342.179759,116.341118,1.163411,0.300,106.157112,36.093418,0.360934
2,Mangrove fringed shoreline,Chale,1.050,371.549894,126.326964,1.263270,5.827,2061.924982,701.054494,7.010545
3,Mangrove fringed shoreline,Chale,0.504,178.343949,60.636943,0.606369,3.676,1300.778485,442.264685,4.422647
4,Mangrove fringed shoreline,Chale,0.546,193.205945,65.690021,0.656900,0.216,76.433121,25.987261,0.259873
...,...,...,...,...,...,...,...,...,...,...
78,Tourist hotels,Neptune,2.576,911.535740,309.922151,3.099222,14.603,5167.374381,1756.907289,17.569073
79,Tourist hotels,Neptune,16.912,5984.430290,2034.706299,20.347063,2.047,724.345364,246.277424,2.462774
80,Tourist hotels,Neptune,0.998,353.149328,120.070771,1.200708,8.171,2891.365888,983.064402,9.830644
81,Tourist hotels,Neptune,1.079,381.811748,129.815994,1.298160,6.114,2163.481953,735.583864,7.355839
82,Tourist hotels,Neptune,3.829,1354.918613,460.672328,4.606723,1.031,364.826610,124.041047,1.240410


- Please  Check for variations in sediment, AGB, and BGB among habitats.

- Sediment is on (sed final ), and biomass is on (biomass final).

- Kind regards

In [32]:
AGB_vs_Habitat = smf.ols(formula='Average_AGB ~ C(Habitat)', data=data_diani).fit()
summary = AGB_vs_Habitat.summary()
print(summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:            Average_AGB   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.059
Method:                 Least Squares   F-statistic:                     2.708
Date:                Fri, 05 Aug 2022   Prob (F-statistic):             0.0508
Time:                        09:44:16   Log-Likelihood:                -193.03
No. Observations:                  83   AIC:                             394.1
Df Residuals:                      79   BIC:                             403.7
Df Model:                           3
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                    2.6607      0.449      5.930      0.000       1.768       3.554
C(Habitat)[T.Mangrove fringed shoreline]    -1.1501      0.887     -1.296      0.199      -2.916       0.616
C(Habitat)[T.Sandy river mouth]              1.6361      1.003      1.631      0.107      -0.361       3.633
C(Habitat)[T.Tourist hotels]                 0.9211      0.635      1.452      0.151      -0.342       2.184
==============================================================================
Omnibus:                       65.179   Durbin-Watson:                   2.095
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              367.731
Skew:                           2.452   Prob(JB):                     1.41e-80
Kurtosis:                      12.071   Cond. No.                         4.53
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [41]:
BGB_vs_Habitat = smf.ols(formula='Average_BGB ~ C(Habitat)', data=data_diani).fit()
summary = BGB_vs_Habitat.summary()
print(summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:            Average_BGB   R-squared:                       0.119
Model:                            OLS   Adj. R-squared:                  0.086
Method:                 Least Squares   F-statistic:                     3.568
Date:                Fri, 05 Aug 2022   Prob (F-statistic):             0.0177
Time:                        09:51:07   Log-Likelihood:                -275.49
No. Observations:                  83   AIC:                             559.0
Df Residuals:                      79   BIC:                             568.7
Df Model:                           3
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                    8.1751      1.212      6.747      0.000       5.763      10.587
C(Habitat)[T.Mangrove fringed shoreline]    -3.0110      2.396     -1.257      0.213      -7.780       1.758
C(Habitat)[T.Sandy river mouth]             -6.9874      2.709     -2.579      0.012     -12.380      -1.594
C(Habitat)[T.Tourist hotels]                -4.6682      1.714     -2.724      0.008      -8.079      -1.257
==============================================================================
Omnibus:                       72.094   Durbin-Watson:                   1.529
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              480.094
Skew:                           2.720   Prob(JB):                    5.61e-105
Kurtosis:                      13.451   Cond. No.                         4.53
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.